-- Reference Data Seed File
-- Generated for Staging Environment Setup

-- RefGoals (6)
INSERT INTO ref_goals (id, title, description, category, type, icon, is_active, created_at) VALUES ('019b34be-2c7a-76d6-815a-ea0a8dcdd68d', 'Emergency Fund', 'Save 3-6 months of expenses', 'risk', 'EMERGENCY_FUND', 'ShieldCheck', True, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_goals (id, title, description, category, type, icon, is_active, created_at) VALUES ('019b34be-2c7b-791d-a0d9-8243b98d6400', 'Max 401(k)', 'Contribute the maximum annual amount to your 401(k)', 'retirement', 'RETIREMENT_401K', 'Briefcase', True, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_goals (id, title, description, category, type, icon, is_active, created_at) VALUES ('019b34be-2c7c-7470-b0cb-6d532eee4adc', 'Pay Off Debt', 'Eliminate high-interest consumer debt', 'financial', 'DEBT_PAYOFF', 'CreditCard', True, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_goals (id, title, description, category, type, icon, is_active, created_at) VALUES ('019b34be-2c7d-7757-aefc-b0acaddc877e', 'Pay Off Mortgage', 'Pay off your mortgage', 'lifestyle', 'MORTGAGE_PAYOFF', 'Home', True, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_goals (id, title, description, category, type, icon, is_active, created_at) VALUES ('019b34be-2c7e-7698-80d6-ca0a6d245a44', 'Health Savings', 'Fund your HSA for medical expenses', 'health', 'HEALTH_SAVINGS', 'HeartPulse', True, NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_goals (id, title, description, category, type, icon, is_active, created_at) VALUES ('019b34be-2c7f-7710-9ef9-699eda2f84d2', 'Other Income', 'Establish additional income sources', 'investing', 'ADDITIONAL_INCOME', 'TrendingUp', True, NOW()) ON CONFLICT (id) DO NOTHING;

-- RefMilestones (6)
INSERT INTO ref_milestones (id, title, description, target_age, category, icon, is_active, sort_order, created_at, updated_at) VALUES ('019ae1e4-55e5-750d-9652-0fe935029854', 'Catch-up Contributions', 'Eligible for additional 401(k) and IRA contributions', 50, 'financial', 'dollar-sign', True, 1, NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_milestones (id, title, description, target_age, category, icon, is_active, sort_order, created_at, updated_at) VALUES ('019ae1e4-55e5-7cf7-ab28-39a9490b1329', 'Early Social Security', 'Eligible for reduced Social Security benefits (75% of full benefit)', 62, 'retirement', 'clock', True, 1, NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_milestones (id, title, description, target_age, category, icon, is_active, sort_order, created_at, updated_at) VALUES ('019ae1e4-55e5-7832-9d63-00ff492f6796', 'Medicare Eligibility', 'Eligible for Medicare health insurance', 65, 'healthcare', 'shield', True, 1, NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_milestones (id, title, description, target_age, category, icon, is_active, sort_order, created_at, updated_at) VALUES ('019ae1e4-55e5-716b-a877-1173f05ba877', 'Full Retirement Age', 'Eligible for full Social Security benefits', 67, 'retirement', 'clock', True, 1, NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_milestones (id, title, description, target_age, category, icon, is_active, sort_order, created_at, updated_at) VALUES ('019ae1e4-55e5-71a2-9692-5fa09641a77d', 'Required Minimum Distributions', 'Must begin taking RMDs from retirement accounts', 73, 'financial', 'dollar-sign', True, 1, NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
INSERT INTO ref_milestones (id, title, description, target_age, category, icon, is_active, sort_order, created_at, updated_at) VALUES ('019ae1e4-55e5-7118-b8eb-b615dd8ea970', 'HSA Triple Tax Advantage', 'Health Savings Account contributions, growth, and withdrawals for medical expenses are all tax-free', 55, 'healthcare', 'shield', True, 2, NOW(), NOW()) ON CONFLICT (id) DO NOTHING;
