"""add user_action_items

Revision ID: 254b887e1dcd
Revises: d1e2f3g4h5i6
Create Date: 2025-12-21 15:04:33.350940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '254b887e1dcd'
down_revision: Union[str, None] = 'd1e2f3g4h5i6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action_items',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user_goals', 'target_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('user_goals', 'current_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_goals', 'current_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('user_goals', 'target_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_table('user_action_items')
    # ### end Alembic commands ###
