"""add value to security holdings

Revision ID: 2a8e8d3374a1
Revises: fb353cffa4ab
Create Date: 2025-12-29 18:11:23.919086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8e8d3374a1'
down_revision: Union[str, None] = 'fb353cffa4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_holdings', sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_holdings', 'value')
    # ### end Alembic commands ###
