"""Rename amount to value in user_goals

Revision ID: 4cf239ccba45
Revises: 826878521655
Create Date: 2025-12-21 23:02:11.450897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf239ccba45'
down_revision: Union[str, None] = '826878521655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_goals', 'target_amount', new_column_name='target_value')
    op.alter_column('user_goals', 'current_amount', new_column_name='current_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_goals', 'target_value', new_column_name='target_amount')
    op.alter_column('user_goals', 'current_value', new_column_name='current_amount')
    # ### end Alembic commands ###
