"""refactor_user_jsonb

Revision ID: 518ec9de2949
Revises: a030b179393e
Create Date: 2025-12-22 16:50:54.869867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '518ec9de2949'
down_revision: Union[str, None] = 'a030b179393e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('personal_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('income', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('liabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('risk', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Data Migration
    op.execute("""
    UPDATE users SET
        personal_info = jsonb_build_object(
            'firstName', first_name,
            'lastName', last_name,
            'currentAge', current_age,
            'targetRetirementAge', target_retirement_age,
            'currentLocation', current_location,
            'maritalStatus', marital_status,
            'dependents', dependents,
            'desiredLifestyle', desired_lifestyle,
            'currency', currency,
            'hasSpouse', has_spouse,
            'spouseFirstName', spouse_first_name,
            'spouseLastName', spouse_last_name,
            'spouseCurrentAge', spouse_current_age,
            'spouseTargetRetirementAge', spouse_target_retirement_age,
            'lifeExpectancy', life_expectancy
        ),
        income = jsonb_build_object(
            'currentIncome', current_income,
            'spouseCurrentIncome', spouse_current_income,
            'otherIncomeSource1', other_income_source_1,
            'otherIncomeAmount1', other_income_amount_1,
            'otherIncomeSource2', other_income_source_2,
            'otherIncomeAmount2', other_income_amount_2,
            'expectedIncomeGrowth', expected_income_growth,
            'spouseExpectedIncomeGrowth', spouse_expected_income_growth,
            'pensionIncome', pension_income,
            'spousePensionIncome', spouse_pension_income,
            'socialSecurityAmount', social_security_amount,
            'socialSecurityStartAge', social_security_start_age,
            'spouseSocialSecurityAmount', spouse_social_security_amount,
            'spouseSocialSecurityStartAge', spouse_social_security_start_age
        ),
        assets = jsonb_build_object(
            'savingsBalance', savings_balance,
            'checkingBalance', checking_balance,
            'investmentBalance', investment_balance,
            'investmentContribution', investment_contribution,
            'retirementAccount401k', retirement_account_401k,
            'retirementAccount401kContribution', retirement_account_401k_contribution,
            'retirementAccountIRA', retirement_account_ira,
            'retirementAccountIRAContribution', retirement_account_ira_contribution,
            'retirementAccountRoth', retirement_account_roth,
            'retirementAccountRothContribution', retirement_account_roth_contribution,
            'hsaBalance', hsa_balance,
            'hsaContribution', hsa_contribution,
            'spouseHsaBalance', spouse_hsa_balance,
            'spouseHsaContribution', spouse_hsa_contribution,
            'realEstateValue', real_estate_value,
            'otherAssetsValue', other_assets_value
        ),
        liabilities = jsonb_build_object(
            'mortgageBalance', mortgage_balance,
            'mortgagePayment', mortgage_payment,
            'mortgageRate', mortgage_rate,
            'mortgageYearsLeft', mortgage_years_left,
            'creditCardDebt', credit_card_debt,
            'studentLoanDebt', student_loan_debt,
            'otherDebt', other_debt,
            'totalMonthlyDebtPayments', total_monthly_debt_payments
        ),
        risk = jsonb_build_object(
            'investmentExperience', investment_experience,
            'riskTolerance', risk_tolerance,
            'investmentTimeline', investment_timeline,
            'marketVolatilityComfort', market_volatility_comfort,
            'investmentRebalancingPreference', investment_rebalancing_preference,
            'preferredInvestmentTypes', preferred_investment_types,
            'inflationRateAssumption', inflation_rate_assumption,
            'investmentReturnAssumption', investment_return_assumption,
            'bondGrowthRateAssumption', bond_growth_rate_assumption
        ),
        expenses = jsonb_build_object(
            'breakdown', expenses,
            'totalMonthlyExpenses', total_monthly_expenses,
            'desiredRetirementSpending', desired_retirement_spending,
            'majorOneTimeExpenses', major_one_time_expenses,
            'majorExpensesDescription', major_expenses_description
        );
    """)
    op.drop_column('users', 'other_income_amount_2')
    op.drop_column('users', 'current_location')
    op.drop_column('users', 'retirement_account_roth_contribution')
    op.drop_column('users', 'risk_tolerance')
    op.drop_column('users', 'mortgage_balance')
    op.drop_column('users', 'savings_balance')
    op.drop_column('users', 'other_assets_value')
    op.drop_column('users', 'other_debt')
    op.drop_column('users', 'investment_rebalancing_preference')
    op.drop_column('users', 'spouse_hsa_balance')
    op.drop_column('users', 'target_retirement_age')
    op.drop_column('users', 'expected_income_growth')
    op.drop_column('users', 'bond_growth_rate_assumption')
    op.drop_column('users', 'mortgage_years_left')
    op.drop_column('users', 'spouse_pension_income')
    op.drop_column('users', 'spouse_target_retirement_age')
    op.drop_column('users', 'total_monthly_expenses')
    op.drop_column('users', 'social_security_amount')
    op.drop_column('users', 'spouse_social_security_start_age')
    op.drop_column('users', 'retirement_account_401k')
    op.drop_column('users', 'investment_return_assumption')
    op.drop_column('users', 'mortgage_payment')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'mortgage_rate')
    op.drop_column('users', 'investment_timeline')
    op.drop_column('users', 'retirement_account_roth')
    op.drop_column('users', 'investment_balance')
    op.drop_column('users', 'real_estate_value')
    op.drop_column('users', 'spouse_hsa_contribution')
    op.drop_column('users', 'other_income_amount_1')
    op.drop_column('users', 'current_income')
    op.drop_column('users', 'dependents')
    op.drop_column('users', 'spouse_expected_income_growth')
    op.drop_column('users', 'student_loan_debt')
    op.drop_column('users', 'major_one_time_expenses')
    op.drop_column('users', 'desired_lifestyle')
    op.drop_column('users', 'retirement_account_401k_contribution')
    op.drop_column('users', 'hsa_balance')
    op.drop_column('users', 'total_monthly_debt_payments')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'spouse_last_name')
    op.drop_column('users', 'checking_balance')
    op.drop_column('users', 'retirement_account_ira')
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'current_age')
    op.drop_column('users', 'investment_experience')
    op.drop_column('users', 'spouse_current_age')
    op.drop_column('users', 'other_income_source_2')
    op.drop_column('users', 'has_spouse')
    op.drop_column('users', 'spouse_social_security_amount')
    op.drop_column('users', 'credit_card_debt')
    op.drop_column('users', 'other_income_source_1')
    op.drop_column('users', 'spouse_current_income')
    op.drop_column('users', 'desired_retirement_spending')
    op.drop_column('users', 'hsa_contribution')
    op.drop_column('users', 'market_volatility_comfort')
    op.drop_column('users', 'preferred_investment_types')
    op.drop_column('users', 'retirement_account_ira_contribution')
    op.drop_column('users', 'social_security_start_age')
    op.drop_column('users', 'pension_income')
    op.drop_column('users', 'investment_contribution')
    op.drop_column('users', 'spouse_first_name')
    op.drop_column('users', 'major_expenses_description')
    op.drop_column('users', 'currency')
    op.drop_column('users', 'inflation_rate_assumption')
    op.drop_column('users', 'life_expectancy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('life_expectancy', sa.INTEGER(), server_default=sa.text('95'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('inflation_rate_assumption', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('3.0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('major_expenses_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('investment_contribution', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pension_income', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('social_security_start_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('retirement_account_ira_contribution', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_investment_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('market_volatility_comfort', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hsa_contribution', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('desired_retirement_spending', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'80000'::numeric"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('spouse_current_income', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('other_income_source_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('credit_card_debt', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_social_security_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_spouse', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('other_income_source_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_current_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('investment_experience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('retirement_account_ira', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('checking_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_monthly_debt_payments', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hsa_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('retirement_account_401k_contribution', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('desired_lifestyle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('major_one_time_expenses', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('student_loan_debt', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_expected_income_growth', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dependents', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_income', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('other_income_amount_1', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_hsa_contribution', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('real_estate_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('investment_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('retirement_account_roth', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('investment_timeline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mortgage_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mortgage_payment', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('investment_return_assumption', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('7.0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('retirement_account_401k', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_social_security_start_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('social_security_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_monthly_expenses', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_target_retirement_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_pension_income', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mortgage_years_left', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bond_growth_rate_assumption', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('4.0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('expected_income_growth', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('target_retirement_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spouse_hsa_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('investment_rebalancing_preference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('other_debt', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('other_assets_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('savings_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mortgage_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('risk_tolerance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('retirement_account_roth_contribution', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('other_income_amount_2', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('users', 'risk')
    op.drop_column('users', 'liabilities')
    op.drop_column('users', 'assets')
    op.drop_column('users', 'income')
    op.drop_column('users', 'personal_info')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
