"""Add value_type to user_goals

Revision ID: 6b4885615740
Revises: 4cf239ccba45
Create Date: 2025-12-21 23:18:15.850284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b4885615740'
down_revision: Union[str, None] = '4cf239ccba45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_goals', sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='money'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_goals', 'value_type')
    # ### end Alembic commands ###
