"""add_is_stale_to_retirement_plan

Revision ID: 826878521655
Revises: 254b887e1dcd
Create Date: 2025-12-21 19:17:40.809099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826878521655'
down_revision: Union[str, None] = '254b887e1dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_plans', sa.Column('is_stale', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retirement_plans', 'is_stale')
    # ### end Alembic commands ###
