"""consolidate_plan_inputs_jsonb

Revision ID: a030b179393e
Revises: a9377ee82200
Create Date: 2025-12-22 16:24:40.264462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a030b179393e'
down_revision: Union[str, None] = 'a9377ee82200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_plans', sa.Column('plan_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('retirement_plans', 'retirement_age')
    op.drop_column('retirement_plans', 'spouse_estimated_social_security_benefit')
    op.drop_column('retirement_plans', 'pension_income')
    op.drop_column('retirement_plans', 'spouse_social_security_start_age')
    op.drop_column('retirement_plans', 'portfolio_growth_rate')
    op.drop_column('retirement_plans', 'spouse_pension_income')
    op.drop_column('retirement_plans', 'desired_annual_retirement_spending')
    op.drop_column('retirement_plans', 'major_one_time_expenses')
    op.drop_column('retirement_plans', 'estimated_social_security_benefit')
    op.drop_column('retirement_plans', 'spouse_end_age')
    op.drop_column('retirement_plans', 'other_retirement_income')
    op.drop_column('retirement_plans', 'social_security_start_age')
    op.drop_column('retirement_plans', 'inflation_rate')
    op.drop_column('retirement_plans', 'major_expenses_description')
    op.drop_column('retirement_plans', 'spouse_start_age')
    op.drop_column('retirement_plans', 'bond_growth_rate')
    op.drop_column('retirement_plans', 'spouse_retirement_age')
    op.drop_column('retirement_plans', 'initial_net_worth')
    
    # Manually added User columns
    op.add_column('users', sa.Column('life_expectancy', sa.Integer(), nullable=False, server_default='95'))
    op.add_column('users', sa.Column('inflation_rate_assumption', sa.Numeric(precision=5, scale=2), nullable=False, server_default='3.0'))
    op.add_column('users', sa.Column('investment_return_assumption', sa.Numeric(precision=5, scale=2), nullable=False, server_default='7.0'))
    op.add_column('users', sa.Column('bond_growth_rate_assumption', sa.Numeric(precision=5, scale=2), nullable=False, server_default='4.0'))
    op.add_column('users', sa.Column('desired_retirement_spending', sa.Numeric(precision=12, scale=2), nullable=False, server_default='80000'))
    op.add_column('users', sa.Column('social_security_start_age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('social_security_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('spouse_social_security_start_age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('spouse_social_security_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('pension_income', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('spouse_pension_income', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('major_one_time_expenses', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('major_expenses_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retirement_plans', sa.Column('initial_net_worth', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('spouse_retirement_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('retirement_plans', sa.Column('bond_growth_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('spouse_start_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('retirement_plans', sa.Column('major_expenses_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('retirement_plans', sa.Column('inflation_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('social_security_start_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('retirement_plans', sa.Column('other_retirement_income', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('spouse_end_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('retirement_plans', sa.Column('estimated_social_security_benefit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('major_one_time_expenses', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('desired_annual_retirement_spending', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('spouse_pension_income', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('portfolio_growth_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('spouse_social_security_start_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('retirement_plans', sa.Column('pension_income', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('spouse_estimated_social_security_benefit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('retirement_plans', sa.Column('retirement_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('retirement_plans', 'plan_overrides')
    # ### end Alembic commands ###
