"""add_goal_amounts

Revision ID: a50da9972910
Revises: 01d63a0df6ae
Create Date: 2025-12-18 22:15:42.665166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50da9972910'
down_revision: Union[str, None] = '01d63a0df6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_goals', sa.Column('target_amount', sa.Float(), nullable=True))
    op.add_column('user_goals', sa.Column('current_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_goals', 'current_amount')
    op.drop_column('user_goals', 'target_amount')
    # ### end Alembic commands ###
