"""migrate_jsonb_analytics

Revision ID: a9377ee82200
Revises: 6b4885615740
Create Date: 2025-12-22 15:04:32.756101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9377ee82200'
down_revision: Union[str, None] = '6b4885615740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annual_snapshots_income')
    op.drop_table('annual_snapshots_assets')
    op.drop_table('annual_snapshots_liabilities')
    op.drop_table('annual_snapshots_expenses')
    op.add_column('annual_snapshots', sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('annual_snapshots', sa.Column('liabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('annual_snapshots', sa.Column('income', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('annual_snapshots', sa.Column('expenses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('annual_snapshots', 'income_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('annual_snapshots', 'expense_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'expenses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'preferred_investment_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferred_investment_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'expenses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('annual_snapshots', 'expense_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('annual_snapshots', 'income_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('annual_snapshots', 'expenses')
    op.drop_column('annual_snapshots', 'income')
    op.drop_column('annual_snapshots', 'liabilities')
    op.drop_column('annual_snapshots', 'assets')
    op.create_table('annual_snapshots_expenses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], name='annual_snapshots_expenses_snapshot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='annual_snapshots_expenses_pkey')
    )
    op.create_table('annual_snapshots_liabilities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], name='annual_snapshots_liabilities_snapshot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='annual_snapshots_liabilities_pkey')
    )
    op.create_table('annual_snapshots_assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('growth', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('contribution', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('withdrawal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], name='annual_snapshots_assets_snapshot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='annual_snapshots_assets_pkey')
    )
    op.create_table('annual_snapshots_income',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], name='annual_snapshots_income_snapshot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='annual_snapshots_income_pkey')
    )
    # ### end Alembic commands ###
