"""baseline_schema

Revision ID: bfc36cb480ac
Revises: 
Create Date: 2025-12-19 22:56:55.784840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfc36cb480ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('current_income', sa.Numeric(), nullable=True),
        sa.Column('spouse_current_income', sa.Numeric(), nullable=True),
        sa.Column('retirement_account_401k', sa.Numeric(), nullable=True),
        sa.Column('retirement_account_roth', sa.Numeric(), nullable=True),
        sa.Column('retirement_account_ira', sa.Numeric(), nullable=True),
        sa.Column('investment_balance', sa.Numeric(), nullable=True),
        sa.Column('savings_balance', sa.Numeric(), nullable=True),
        sa.Column('checking_balance', sa.Numeric(), nullable=True),
        sa.Column('mortgage_balance', sa.Numeric(), nullable=True),
        sa.Column('mortgage_payment', sa.Numeric(), nullable=True),
        sa.Column('student_loan_debt', sa.Numeric(), nullable=True),
        sa.Column('credit_card_debt', sa.Numeric(), nullable=True),
        sa.Column('other_debt', sa.Numeric(), nullable=True),
        sa.Column('total_monthly_expenses', sa.Numeric(), nullable=True),
        sa.Column('expenses', sa.JSON(), nullable=True),
        sa.Column('hsa_balance', sa.Numeric(), nullable=True),
        sa.Column('spouse_hsa_balance', sa.Numeric(), nullable=True),
        sa.Column('other_income_amount_1', sa.Numeric(), nullable=True),
        sa.Column('other_income_amount_2', sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # GoalType Enum
    goal_type_enum = sa.Enum('EMERGENCY_FUND', 'RETIREMENT_401K', 'DEBT_PAYOFF', 'MORTGAGE_PAYOFF', 'HEALTH_SAVINGS', 'ADDITIONAL_INCOME', 'CUSTOM', name='goaltype')
    goal_type_enum.create(op.get_bind())

    op.create_table('ref_goals',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', goal_type_enum, nullable=False, server_default='CUSTOM'),
        sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('default_target_offset', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('ref_milestones',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('target_age', sa.Integer(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('retirement_plans',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('start_age', sa.Integer(), nullable=False),
        sa.Column('end_age', sa.Integer(), nullable=False),
        sa.Column('retirement_age', sa.Integer(), nullable=False),
        sa.Column('life_expectancy', sa.Integer(), nullable=False),
        sa.Column('inflation_rate', sa.Numeric(), nullable=False),
        sa.Column('portfolio_growth_rate', sa.Numeric(), nullable=False),
        sa.Column('bond_growth_rate', sa.Numeric(), nullable=False),
        sa.Column('annual_savings_rate', sa.Numeric(), nullable=False),
        sa.Column('total_lifetime_tax', sa.Numeric(), nullable=True),
        sa.Column('social_security_start_age', sa.Integer(), nullable=True),
        sa.Column('estimated_social_security_benefit', sa.Numeric(), nullable=True),
        sa.Column('pension_income', sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_goals',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('progress', sa.Integer(), nullable=False),
        sa.Column('target_date', sa.DateTime(), nullable=True),
        sa.Column('ref_goal_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column('current_amount', sa.Numeric(), nullable=False),
        sa.Column('target_amount', sa.Numeric(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(['ref_goal_id'], ['ref_goals.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_milestones',
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('target_year', sa.Integer(), nullable=True),
        sa.Column('target_age', sa.Integer(), nullable=True),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('plan_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column('milestone_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['plan_id'], ['retirement_plans.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('annual_snapshots',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('plan_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=False),
        sa.Column('gross_income', sa.Numeric(), nullable=False),
        sa.Column('net_income', sa.Numeric(), nullable=False),
        sa.Column('total_expenses', sa.Numeric(), nullable=False),
        sa.Column('total_assets', sa.Numeric(), nullable=False),
        sa.Column('total_liabilities', sa.Numeric(), nullable=False),
        sa.Column('net_worth', sa.Numeric(), nullable=False),
        sa.Column('taxes_paid', sa.Numeric(), nullable=False),
        sa.Column('cumulative_tax', sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(['plan_id'], ['retirement_plans.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('annual_snapshot_assets',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('snapshot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('balance', sa.Numeric(), nullable=False),
        sa.Column('growth', sa.Numeric(), nullable=False),
        sa.Column('contribution', sa.Numeric(), nullable=False),
        sa.Column('withdrawal', sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('annual_snapshot_liabilities',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('snapshot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('balance', sa.Numeric(), nullable=False),
        sa.Column('payment', sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('annual_snapshot_incomes',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('snapshot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('amount', sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('annual_snapshot_expenses',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('snapshot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('amount', sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(['snapshot_id'], ['annual_snapshots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
