"""add_hsa_fields

Revision ID: c6c0bfa9f65f
Revises: a50da9972910
Create Date: 2025-12-19 16:02:15.012908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c0bfa9f65f'
down_revision: Union[str, None] = 'a50da9972910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hsa_balance', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('users', sa.Column('hsa_contribution', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('users', sa.Column('spouse_hsa_balance', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('users', sa.Column('spouse_hsa_contribution', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spouse_hsa_contribution')
    op.drop_column('users', 'spouse_hsa_balance')
    op.drop_column('users', 'hsa_contribution')
    op.drop_column('users', 'hsa_balance')
    # ### end Alembic commands ###
