"""add_subscription_fields_to_user

Revision ID: f3f5ec9b6293
Revises: 2a8e8d3374a1
Create Date: 2026-01-02 18:23:18.262343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f3f5ec9b6293'
down_revision: Union[str, None] = '2a8e8d3374a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("'none'")))
    op.add_column('users', sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('users', 'current_period_end')
    op.drop_column('users', 'variant_id')
    op.drop_column('users', 'customer_id')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
